server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/remio_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    virtual-host: qjkjkopp
    username: qjkjkopp
    password: GQfxU80cRycrAO9jQL9E9zwPehdCfuPu
    addresses: amqps://qjkjkopp:GQfxU80cRycrAO9jQL9E9zwPehdCfuPu@jaragua.lmq.cloudamqp.com/qjkjkopp
    ssl:
      enabled: true



  mail:
    host: smtp.gmail.com
    port: 587
    username: keverson.teodoro@youxlab.com.br
    password: ihqk yhxo wfqu rbkb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

broker:
  queue:
    email:
      name: remio_queue