server:
  port: 8088

spring:
  application:
    name: remio
  datasource:
    url: jdbc:postgresql://localhost:5432/remio_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  rabbitmq:
    virtual-host: qjkjkopp
    username: qjkjkopp
    password: GQfxU80cRycrAO9jQL9E9zwPehdCfuPu
    addresses: amqps://qjkjkopp:GQfxU80cRycrAO9jQL9E9zwPehdCfuPu@jaragua.lmq.cloudamqp.com/qjkjkopp
    ssl:
      enabled: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: keverson.teodoro@youxlab.com.br
    password: wchx tlyn fmij xvnn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#  rabbitmq:
#    addresses: amqps://qjkjkopp:GQfxU80cRycrAO9jQL9E9zwPehdCfuPu@jaragua.lmq.cloudamqp.com/qjkjkopp
#    ssl:
#      enabled: true



broker:
  queue:
    email:
      name: remio_queue


api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}